[tool.poetry]
name = "uwhoisd"
version = "0.1.0"
description = "Universal domain WHOIS proxy server."
authors = ["Raphaël Vinot <raphael@vinot.info>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
tornado = "^6.1"
redis = "^3.5.3"
beautifulsoup4 = "^4.9.3"
publicsuffix2 = "^2.20191221"

[tool.poetry.dev-dependencies]
coverage = "^5.5"
nose = "^1.3.7"
Sphinx = "^4.1.2"
mypy = "^0.910"
types-redis = "^3.5.6"

[tool.poetry.scripts]
uwhoisd = 'uwhoisd:main'
run_backend = 'bin.run_backend:main'
start = 'bin.start:main'
stop = 'bin.stop:main'
shutdown = 'bin.shutdown:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
