[tool.poetry]
name = "uwhoisd"
version = "0.1.0"
description = "Universal domain WHOIS proxy server."
authors = ["Raphaël Vinot <raphael@vinot.info>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
tornado = "^6.2"
redis = "^4.3.4"
beautifulsoup4 = "^4.11.1"
publicsuffix2 = "^2.20191221"

[tool.poetry.dev-dependencies]
Sphinx = "^5.1.1"
mypy = "^0.971"
types-redis = "^4.3.19"

[tool.poetry.scripts]
uwhoisd = 'uwhoisd:main'
run_backend = 'bin.run_backend:main'
start = 'bin.start:main'
stop = 'bin.stop:main'
shutdown = 'bin.shutdown:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
