[tool.poetry]
name = "uwhoisd"
version = "0.1.0"
description = "Universal domain WHOIS proxy server."
authors = ["Raphaël Vinot <raphael@vinot.info>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
tornado = "^6.3.2"
redis = "^4.5.5"
beautifulsoup4 = "^4.12.2"
publicsuffix2 = "^2.20191221"

[tool.poetry.dev-dependencies]
Sphinx = "^7.0.1"
mypy = "^1.3.0"
types-redis = "^4.5.5.2"

[tool.poetry.scripts]
uwhoisd = 'uwhoisd:main'
run_backend = 'bin.run_backend:main'
start = 'bin.start:main'
stop = 'bin.stop:main'
shutdown = 'bin.shutdown:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
